[build-system]
requires = ["setuptools>=65", "wheel >= 0.38", "pep517>=0.11"]
build-backend = "setuptools.build_meta"

[project]
name = "solaredge"
version = "0.0.1"
dependencies = [
    "requests",
    "python-dotenv",
    "influxdb",
    "argparse",
    "ujson",
    "ciso8601",
]
authors = [
  { name="Nick Clayton"},
]
description = "API for Solaredge devices"
readme = "README.md"
requires-python = ">=3.11"
classifiers = [
    "Programming Language :: Python :: 3",
    "License :: OSI Approved :: MIT License",
    "Operating System :: OS Independent",
]

[project.urls]
"Homepage" = "https://github.com/claytonn73/solaredge-api"
